FROM madnificent/ember:4.3.0 as builder

LABEL maintainer="info@redpencil.io"

WORKDIR /app
COPY package.json .
RUN npm install

COPY . .
RUN ember build --environment production

FROM redpencil/fastboot-app-server:1.1.0

COPY --from=builder /app/dist /app
